package com.gtnewhorizon.cropsnh.api;

public class CropsNHCrops {

    public static ICropCard Weed;
    public static ICropCard Carrot;
    public static ICropCard Cocoa;
    public static ICropCard Melon;
    public static ICropCard Potato;
    public static ICropCard Pumpkin;
    public static ICropCard Wheat;
    public static ICropCard RedMushroom;
    public static ICropCard BrownMushroom;
    public static ICropCard Dandelion;
    public static ICropCard Poppy;
    public static ICropCard BlueOrchid;
    public static ICropCard Allium;
    public static ICropCard AzureBluet;
    public static ICropCard RedTulip;
    public static ICropCard OrangeTulip;
    public static ICropCard WhiteTulip;
    public static ICropCard PinkTulip;
    public static ICropCard OxeyeDaisy;
    public static ICropCard Cactus;
    public static ICropCard SugarCane;
    public static ICropCard Netherwart;
    public static ICropCard BonsaiOak;
    public static ICropCard BonsaiSpruce;
    public static ICropCard BonsaiBirch;
    public static ICropCard BonsaiJungle;
    public static ICropCard BonsaiAcacia;
    public static ICropCard BonsaiDarkOak;
    public static ICropCard BonsaiRubber;
    /** Gold Crop */
    public static ICropCard Aurelia;
    public static ICropCard Coffee;
    /** Low Quality Copper Crop */
    public static ICropCard Cyprium;
    /** Iron Crop */
    public static ICropCard Ferru;
    public static ICropCard Hops;
    /** Low Quality Lead Crop */
    public static ICropCard Plumbiscus;
    /** Redstone Crop */
    public static ICropCard Redwheat;
    /** Low Quality Silver Crop */
    public static ICropCard Shining;
    /** Low Quality Tin Crop */
    public static ICropCard Stagnium;
    public static ICropCard StickReed;
    public static ICropCard Venomilia;
    public static ICropCard TerraWart;
    public static ICropCard StoneLily;
    public static ICropCard SandLily;
    public static ICropCard ClayLily;
    public static ICropCard NetherStoneLily;
    public static ICropCard SoulSandLily;
    public static ICropCard EndStoneLily;
    public static ICropCard RedGraniteLily;
    public static ICropCard BlackGraniteLily;
    public static ICropCard BasaltLily;
    public static ICropCard MarbleLily;
    public static ICropCard AndesiteLily;
    public static ICropCard DioriteLily;
    public static ICropCard GraniteLily;
    public static ICropCard BonsaiSlimy;
    public static ICropCard AluminiumOreBerry;
    public static ICropCard CopperOreBerry;
    public static ICropCard EssenceOreBerry;
    public static ICropCard GoldOreBerry;
    public static ICropCard IronOreBerry;
    public static ICropCard TinOreBerry;
    public static ICropCard ArditeOreBerry;
    public static ICropCard CobaltOreBerry;
    public static ICropCard ThaumiumOreBerry;
    public static ICropCard VoidOreBerry;
    public static ICropCard ThauminiteOreBerry;
    public static ICropCard Cinderpearl;
    public static ICropCard Shimmerleaf;
    public static ICropCard ManaBean;
    /** Primordial Perl Crop */
    public static ICropCard PrimordialBerry;
    public static ICropCard KnightmetalBerry;
    public static ICropCard Torchberry;
    public static ICropCard Moss;
    public static ICropCard Bamboo;
    public static ICropCard BoPBerry;
    public static ICropCard Eyebulb;
    public static ICropCard FloweringVine;
    public static ICropCard Glowflower;
    public static ICropCard GlowingCoral;
    public static ICropCard Glowshroom;
    public static ICropCard Ivy;
    public static ICropCard Turnip;
    public static ICropCard WildCarrot;
    public static ICropCard Belladonna;
    public static ICropCard EmberMoss;
    public static ICropCard Garlic;
    public static ICropCard GlintWeed;
    public static ICropCard Mandrake;
    public static ICropCard Snowbell;
    public static ICropCard SpanishMoss;
    public static ICropCard WaterArtichoke;
    public static ICropCard Wolfsbane;
    public static ICropCard Blightberry;
    public static ICropCard BlueGlowshroom;
    public static ICropCard Duskberry;
    public static ICropCard GreenGlowshroom;
    public static ICropCard PurpleGlowshroom;
    public static ICropCard Skyberry;
    public static ICropCard Stingberry;
    public static ICropCard Thornvine;
    public static ICropCard Barley;
    public static ICropCard Blackberry;
    public static ICropCard Blueberry;
    public static ICropCard Cotton;
    public static ICropCard Raspberry;
    public static ICropCard Maloberry;
    public static ICropCard SaguaroCactus;
    /** <strike>Loud</strike> Fish Oil Crop */
    public static ICropCard Cucumber;
    public static ICropCard Goldfish;
    public static ICropCard Huckleberry;
    /** Magic Modifier Crop */
    public static ICropCard MagicalNightshade;
    /** Paper Crop */
    public static ICropCard Papyrus;
    public static ICropCard SpaceFlower;
    public static ICropCard Strawberry;
    /** Sugar Crop */
    public static ICropCard SugarBeet;
    public static ICropCard Vine;
    /** Lilipad Crop */
    public static ICropCard Waterlily;
    public static ICropCard Hemp;
    /** Salt Crop */
    public static ICropCard SaltyRoot;
    /** Silver Crop */
    public static ICropCard Argentia;
    /** Bauxite and Aluminum Crop */
    public static ICropCard Bauxia;
    /** Squid Ink Crop */
    public static ICropCard Blackthorn;
    /** Blaze Crop */
    public static ICropCard Blazereed;
    /** Emerald Crop */
    public static ICropCard BobsYerUncleRanks;
    public static ICropCard Canola;
    public static ICropCard Chilly;
    /** Copper Crop */
    public static ICropCard Coppon;
    /** Leather Crop */
    public static ICropCard Corium;
    /** Rotten Flesh and Bones Crop */
    public static ICropCard Corpseplant;
    /** Gunpowder Crop */
    public static ICropCard Creeperweed;
    /** Cyan Dye Crop */
    public static ICropCard Cyazint;
    /** Diamond Crop */
    public static ICropCard Diareed;
    /** Chicken Crop */
    public static ICropCard EggPlant;
    /** Enderpearl crop */
    public static ICropCard Enderbloom;
    /** Quartz crop */
    public static ICropCard EvilOre;
    /** Fertilizer Crop */
    public static ICropCard Fertilia;
    public static ICropCard Flax;
    /** Zinc Crop */
    public static ICropCard Galvania;
    /** Garnet Crop */
    public static ICropCard Garnydinia;
    /** Medium Quality Glowstone Crop */
    public static ICropCard Glowheat;
    /** Thorium Crop */
    public static ICropCard GodOfThunder;
    public static ICropCard Grape;
    /** Indigo Dye Crop */
    public static ICropCard Indigo;
    /** Iridium Crop */
    public static ICropCard Iridine;
    /** Lapis Crop */
    public static ICropCard Lazulia;
    public static ICropCard Lemon;
    /** Living Root Crop */
    public static ICropCard Liveroot;
    /** General Meat Crop */
    public static ICropCard Meatrose;
    /** Mica Crop */
    public static ICropCard Micadia;
    /** Milk Crop */
    public static ICropCard Milkwart;
    /** Nickel Crop */
    public static ICropCard Nickelback;
    public static ICropCard OilBerry;
    /** Olivine Crop */
    public static ICropCard Olivia;
    public static ICropCard Onion;
    /** Osmium Crop */
    public static ICropCard Osmianth;
    /** Platinum Crop */
    public static ICropCard Platina;
    /** Lead Crop */
    public static ICropCard Plumbilia;
    /** Manganese Crop */
    public static ICropCard Pyrolusium;
    public static ICropCard PurpleTulip;
    /** Uranium Crop */
    public static ICropCard Reactoria;
    /** Sapphire Crop */
    public static ICropCard Sapphirum;
    /** Tungsten Crop */
    public static ICropCard Scheelinium;
    public static ICropCard Slimeplant;
    public static ICropCard Spidernip;
    /** Naquadah Crop */
    public static ICropCard Stargatium;
    /** Nether Star and Wither Crop */
    public static ICropCard Starwart;
    /** Steeleaf Crop */
    public static ICropCard Steeleafranks;
    public static ICropCard Tea;
    /** Ghast Crop */
    public static ICropCard Tearstalks;
    /** Tin Crop */
    public static ICropCard Tine;
    /** Titanium Crop */
    public static ICropCard Titania;
    public static ICropCard Tomato;
    /** UUM and UUA Crop */
    public static ICropCard Transformium;
    /** Plutonium 241 and Spinel Crop */
    public static ICropCard Trollplant;
    /** Coal and Wither Skeleton Crop */
    public static ICropCard Withereed;
    /** Zombie Crop */
    public static ICropCard Zomplant;
}
